name: berkeley-stat-course

channels:
- conda-forge

dependencies:
  - ipykernel==6.29.0
  - notebook=7.0.7
  - jupyterlab==4.1.0
  - jupyterlab-myst==2.1.0
  - nodejs>=18.0
  - libwebp==1.3.2
  - matplotlib==3.8.2
  - numpy==1.26.4
