name: berkeley-stat-course

channels:
- conda-forge

dependencies:
  - ipykernel==6.29.5
  - notebook=7.3.2
  - jupyterlab==4.3.4
  - jupyterlab-myst==2.4.2
  - nodejs>=20.0
  - libwebp==1.5.0
#  - pip:
#    - foo==7.6.0
